#access-token:
#    private: "access-refresh-token-keys/access-token-private.key"
#    public: "access-refresh-token-keys/access-token-public.key"

#refresh-token:
#    private: "access-refresh-token-keys/refresh-token-private.key"
#    public: "access-refresh-token-keys/refresh-token-public.key"

spring:
    cloud:
        config:
            uri: http://localhost:8888
            username: configuser
            password: configpassword
    profiles:
        active: dev
  #  data:
  #      mongodb:
 #           uri: mongodb://localhost:27017
 #           database: oauth2

logging:
    level:
      org.springframework.security: DEBUG