server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jhans10/Iventory-Management
          clone-on-start: true
          default-label: main
  security:
    user:
      name: configuser
      password: configpassword
logging:
  level:
    org.springframework: DEBUG




